/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
/**
 *
 * @author dav
 */
public class CalcFrame extends javax.swing.JFrame {

    double expression1, expression2;
    double solution;
    String operator;
    boolean solved = false;
    /**
     * Creates new form CalcFrame
     */
    public CalcFrame() {
        initComponents();
    }

    public void displayValue(JButton button){
        String value;
        value = jTextPane_screen.getText() + button.getText();
        jTextPane_screen.setText(value); 
    }
    
    public void getExpression1(){
        expression1 = Double.parseDouble(jTextPane_screen.getText());
        jTextPane_screen.setText("");        
    }
    
    public void reset(){
        expression1 = 0;
        expression2 = 0;
        solution = 0;
        operator = null;
        solved = false;
        jTextPane_screen.setText("");
    }
    
    public void solve(){
        if(!operator.equalsIgnoreCase("²") && !operator.equalsIgnoreCase("√"))
            expression2 = Double.parseDouble(jTextPane_screen.getText());
        
        switch(operator){
            case "+": 
                solution = expression1 + expression2;
                jTextPane_screen.setText(Double.toString(solution));
                break;
            case "-":
                solution = expression1 - expression2;
                jTextPane_screen.setText(Double.toString(solution));
                break;
            case "x":
                solution = expression1 * expression2;
                jTextPane_screen.setText(Double.toString(solution));
                break;
            case "/":
                solution = expression1 / expression2;
                jTextPane_screen.setText(Double.toString(solution));   
                break;
            case "²":
                solution = expression1 * expression1;
                jTextPane_screen.setText(Double.toString(solution));
                break;
            case "√":
                solution = Math.sqrt(expression1);
                jTextPane_screen.setText(Double.toString(solution));            
        }
        solved = true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_screen = new javax.swing.JTextPane();
        jButton_7 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_point = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_divide = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_multiply = new javax.swing.JButton();
        jButton_minus = new javax.swing.JButton();
        jButton_plus = new javax.swing.JButton();
        jButton_power = new javax.swing.JButton();
        jButton_root = new javax.swing.JButton();
        jButton_equals = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(158, 158, 159));

        jPanel1.setBackground(new java.awt.Color(181, 181, 181));

        jTextPane_screen.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextPane_screen);

        jButton_7.setBackground(new java.awt.Color(181, 181, 181));
        jButton_7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_7.setForeground(new java.awt.Color(0, 0, 0));
        jButton_7.setText("7");
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });

        jButton_8.setBackground(new java.awt.Color(181, 181, 181));
        jButton_8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_8.setForeground(new java.awt.Color(0, 0, 0));
        jButton_8.setText("8");
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });

        jButton_9.setBackground(new java.awt.Color(181, 181, 181));
        jButton_9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_9.setForeground(new java.awt.Color(0, 0, 0));
        jButton_9.setText("9");
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });

        jButton_4.setBackground(new java.awt.Color(181, 181, 181));
        jButton_4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_4.setForeground(new java.awt.Color(0, 0, 0));
        jButton_4.setText("4");
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_5.setBackground(new java.awt.Color(181, 181, 181));
        jButton_5.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_5.setForeground(new java.awt.Color(0, 0, 0));
        jButton_5.setText("5");
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton_6.setBackground(new java.awt.Color(181, 181, 181));
        jButton_6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_6.setForeground(new java.awt.Color(0, 0, 0));
        jButton_6.setText("6");
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });

        jButton_1.setBackground(new java.awt.Color(181, 181, 181));
        jButton_1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_1.setForeground(new java.awt.Color(0, 0, 0));
        jButton_1.setText("1");
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_2.setBackground(new java.awt.Color(181, 181, 181));
        jButton_2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_2.setForeground(new java.awt.Color(0, 0, 0));
        jButton_2.setText("2");
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_3.setBackground(new java.awt.Color(181, 181, 181));
        jButton_3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_3.setForeground(new java.awt.Color(0, 0, 0));
        jButton_3.setText("3");
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_point.setBackground(new java.awt.Color(181, 181, 181));
        jButton_point.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_point.setForeground(new java.awt.Color(0, 0, 0));
        jButton_point.setText(".");
        jButton_point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pointActionPerformed(evt);
            }
        });

        jButton_0.setBackground(new java.awt.Color(181, 181, 181));
        jButton_0.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_0.setForeground(new java.awt.Color(0, 0, 0));
        jButton_0.setText("0");
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });

        jButton_divide.setBackground(new java.awt.Color(181, 181, 181));
        jButton_divide.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_divide.setForeground(new java.awt.Color(0, 0, 0));
        jButton_divide.setText("/");
        jButton_divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_divideActionPerformed(evt);
            }
        });

        jButton_delete.setBackground(new java.awt.Color(181, 181, 181));
        jButton_delete.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_delete.setForeground(new java.awt.Color(0, 0, 0));
        jButton_delete.setText("del");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_clear.setBackground(new java.awt.Color(181, 181, 181));
        jButton_clear.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_clear.setForeground(new java.awt.Color(0, 0, 0));
        jButton_clear.setText("clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_multiply.setBackground(new java.awt.Color(181, 181, 181));
        jButton_multiply.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_multiply.setForeground(new java.awt.Color(0, 0, 0));
        jButton_multiply.setText("x");
        jButton_multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiplyActionPerformed(evt);
            }
        });

        jButton_minus.setBackground(new java.awt.Color(181, 181, 181));
        jButton_minus.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_minus.setForeground(new java.awt.Color(0, 0, 0));
        jButton_minus.setText("-");
        jButton_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_minusActionPerformed(evt);
            }
        });

        jButton_plus.setBackground(new java.awt.Color(181, 181, 181));
        jButton_plus.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_plus.setForeground(new java.awt.Color(0, 0, 0));
        jButton_plus.setText("+");
        jButton_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plusActionPerformed(evt);
            }
        });

        jButton_power.setBackground(new java.awt.Color(181, 181, 181));
        jButton_power.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_power.setForeground(new java.awt.Color(0, 0, 0));
        jButton_power.setText("x²");
        jButton_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_powerActionPerformed(evt);
            }
        });

        jButton_root.setBackground(new java.awt.Color(181, 181, 181));
        jButton_root.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_root.setForeground(new java.awt.Color(0, 0, 0));
        jButton_root.setText("√");
        jButton_root.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_rootActionPerformed(evt);
            }
        });

        jButton_equals.setBackground(new java.awt.Color(181, 181, 181));
        jButton_equals.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton_equals.setForeground(new java.awt.Color(0, 0, 0));
        jButton_equals.setText("=");
        jButton_equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_equalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_9)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_multiply, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jButton_divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_clear))
                            .addComponent(jButton_equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_power, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_root, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_point, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_3)
                            .addComponent(jButton_plus))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_7)
                    .addComponent(jButton_8)
                    .addComponent(jButton_9)
                    .addComponent(jButton_divide)
                    .addComponent(jButton_clear)
                    .addComponent(jButton_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_4)
                    .addComponent(jButton_5)
                    .addComponent(jButton_6)
                    .addComponent(jButton_multiply)
                    .addComponent(jButton_power)
                    .addComponent(jButton_root))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_1)
                    .addComponent(jButton_2)
                    .addComponent(jButton_3)
                    .addComponent(jButton_minus)
                    .addComponent(jButton_equals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_point)
                    .addComponent(jButton_0)
                    .addComponent(jButton_plus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_0);
    }//GEN-LAST:event_jButton_0ActionPerformed
  
    private void jButton_pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pointActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_point);
    }//GEN-LAST:event_jButton_pointActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_1);
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_2);
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_3);
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_4);
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_5);
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_6);
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_7);
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_8);
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        // TODO add your handling code here:
        if(solved)
            reset();
        displayValue(jButton_9);
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plusActionPerformed
        // TODO add your handling code here:
        if(solved)
            solved = false;
        getExpression1();
        operator = "+";
    }//GEN-LAST:event_jButton_plusActionPerformed

    private void jButton_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_minusActionPerformed
        // TODO add your handling code here:
        if(solved)
            solved = false;
        getExpression1();
        operator = "-";
    }//GEN-LAST:event_jButton_minusActionPerformed

    private void jButton_multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiplyActionPerformed
        // TODO add your handling code here:
        if(solved)
            solved = false;
        getExpression1();
        operator = "x";
    }//GEN-LAST:event_jButton_multiplyActionPerformed

    private void jButton_divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_divideActionPerformed
        // TODO add your handling code here:
        if(solved)
            solved = false;
        getExpression1();
        operator = "/";
    }//GEN-LAST:event_jButton_divideActionPerformed

    private void jButton_equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_equalsActionPerformed
        // TODO add your handling code here:
        solve();
    }//GEN-LAST:event_jButton_equalsActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_powerActionPerformed
        // TODO add your handling code here:
        if(solved)
            solved = false;
        expression1 = Double.parseDouble(jTextPane_screen.getText());
        operator = "²";
        jTextPane_screen.setText(jTextPane_screen.getText() + operator);
    }//GEN-LAST:event_jButton_powerActionPerformed

    private void jButton_rootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_rootActionPerformed
        // TODO add your handling code here:
        if(solved)
            solved = false;
        expression1 = Double.parseDouble(jTextPane_screen.getText());
        operator = "√";
        jTextPane_screen.setText(operator + jTextPane_screen.getText());
    }//GEN-LAST:event_jButton_rootActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder(jTextPane_screen.getText());
        sb = sb.deleteCharAt(sb.length() - 1);
        jTextPane_screen.setText(sb.toString());
    }//GEN-LAST:event_jButton_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_divide;
    private javax.swing.JButton jButton_equals;
    private javax.swing.JButton jButton_minus;
    private javax.swing.JButton jButton_multiply;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_point;
    private javax.swing.JButton jButton_power;
    private javax.swing.JButton jButton_root;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_screen;
    // End of variables declaration//GEN-END:variables
}
